# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "google_drive"
gem "uri"
gem "httparty"
gem "google-api-client", "~> 0.34"
gem "spreadsheet"
gem 'comtele_sdk'