# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "watir", '6.8.4'
gem "gemoji", '3.0.1'
gem "faker", '2.12'